// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.API.Data;

#nullable disable

namespace MyApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.API.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Consumer electronics and software",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Electronics, appliances, and mobile devices",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Entertainment and consumer electronics",
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sportswear and footwear",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Sportswear, apparel and accessories",
                            Name = "Adidas"
                        });
                });

            modelBuilder.Entity("MyApp.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Devices and gadgets",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Men and women clothing",
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fiction, non-fiction, academic",
                            Name = "Books"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Furniture & home accessories",
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("MyApp.API.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 12, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TotalAmount = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 12, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = "PROCESSING",
                            TotalAmount = 349.99m
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 12, 3, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Status = "Delivered",
                            TotalAmount = 129.99m
                        });
                });

            modelBuilder.Entity("MyApp.API.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 2,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 349.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 129.99m
                        });
                });

            modelBuilder.Entity("MyApp.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(MAX)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Description = "Latest Apple smartphone",
                            ImageUrl = "https://picsum.photos/seed/iphone14-main/200",
                            Name = "iPhone 14",
                            Price = 999.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 1,
                            Description = "Flagship Samsung smartphone",
                            ImageUrl = "https://picsum.photos/seed/galaxys23-main/200",
                            Name = "Samsung Galaxy S23",
                            Price = 899.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            CategoryId = 1,
                            Description = "Noise-cancelling wireless headphones",
                            ImageUrl = "https://picsum.photos/seed/sonyxm5-main/200",
                            Name = "Sony WH-1000XM5",
                            Price = 349.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 4,
                            CategoryId = 2,
                            Description = "Popular athletic sneakers",
                            ImageUrl = "https://picsum.photos/seed/nikeairmax-main/200",
                            Name = "Nike Air Max",
                            Price = 129.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 5,
                            CategoryId = 2,
                            Description = "Lightweight running T-shirt",
                            ImageUrl = "https://picsum.photos/seed/adidastee-main/200",
                            Name = "Adidas Running Tee",
                            Price = 29.99m,
                            StockQuantity = 200
                        });
                });

            modelBuilder.Entity("MyApp.API.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://picsum.photos/seed/iphone14-main/200",
                            IsMain = true,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://picsum.photos/seed/iphone14-2/200",
                            IsMain = false,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://picsum.photos/seed/galaxys23-main/200",
                            IsMain = true,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://picsum.photos/seed/galaxys23-2/200",
                            IsMain = false,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://picsum.photos/seed/sonyxm5-main/200",
                            IsMain = true,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://picsum.photos/seed/sonyxm5-2/200",
                            IsMain = false,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://picsum.photos/seed/nikeairmax-main/200",
                            IsMain = true,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://picsum.photos/seed/nikeairmax-2/200",
                            IsMain = false,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://picsum.photos/seed/adidastee-main/200",
                            IsMain = true,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://picsum.photos/seed/adidastee-2/200",
                            IsMain = false,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("MyApp.API.Entities.OrderItem", b =>
                {
                    b.HasOne("MyApp.API.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.API.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyApp.API.Entities.Product", b =>
                {
                    b.HasOne("MyApp.API.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.API.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApp.API.Entities.ProductImage", b =>
                {
                    b.HasOne("MyApp.API.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyApp.API.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyApp.API.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyApp.API.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyApp.API.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
